apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.service.name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
